### ISSUE TITLE
Any routes after 'buzzybee.io/<vaildRoute>/' cause an error. 

### ISSUE THREAD

**Issue by thisisrai** [buzzybeeio/buzzybeeWeb#20]
Example urls that will trigger error: 

1) buzzybee.io/contacts/
2) buzzybee.io/lkajsdflkj/
3) buzzybee.io/raiisawesome/

**Comment by yogimasterson** [comment]
I don't get it. I'm typing in the routes and don't see any issues in case of invalid routes it just defaults to the home page.

**Comment by thisisrai** [comment]
Try http://www.buzzybee.io/contact/aslfdjsa/

**Comment by thisisrai** [comment]
Fixed
