### ISSUE TITLE
Update contact form

### ISSUE THREAD

**Issue by buzzybeeio** [buzzybeeio/buzzybeeWeb#24]
Our contact form isn't the most aesthetic, would someone like to take a jab at making it look better?

**Comment by connor11528** [comment]
I'm down to take a stab at it. I had a question though. I see the Contact.css but don't understand how the `form-control contact` classes get applied on the input field. Where do those come from?

**Comment by connor11528** [comment]
nvm I'm retar***, was looking at the wrong branch. I think this got resolved with 59dba61d5b5a913f3cf9425673fa7c1923a60f7d

**Comment by thisisrai** [comment]
You're good! Yea, I forgot to mark this as resolved! Thanks!
